// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9-Jrj66fdO2PgauU515ouKTAborIUalk',
    appId: '1:108609438615:web:a3a008e8052c48dc2cbad2',
    messagingSenderId: '108609438615',
    projectId: 'notes-app-d1fcd',
    authDomain: 'notes-app-d1fcd.firebaseapp.com',
    storageBucket: 'notes-app-d1fcd.appspot.com',
    measurementId: 'G-P4CPL820EP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrI8JXaVJfRu95qa0b5zC59hQ20wMZUxc',
    appId: '1:108609438615:android:fdc7f38f316c735a2cbad2',
    messagingSenderId: '108609438615',
    projectId: 'notes-app-d1fcd',
    storageBucket: 'notes-app-d1fcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV4IgTD21AK7WfBS1bOwggcBAI420UI8Q',
    appId: '1:108609438615:ios:6ce7d08f7fdcb8742cbad2',
    messagingSenderId: '108609438615',
    projectId: 'notes-app-d1fcd',
    storageBucket: 'notes-app-d1fcd.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV4IgTD21AK7WfBS1bOwggcBAI420UI8Q',
    appId: '1:108609438615:ios:765ed3646aa925512cbad2',
    messagingSenderId: '108609438615',
    projectId: 'notes-app-d1fcd',
    storageBucket: 'notes-app-d1fcd.appspot.com',
    iosBundleId: 'com.example.notesApp.RunnerTests',
  );
}
